### ISSUE TITLE
Next 15 incompatibility

### ISSUE THREAD

**Issue by sannajammeh** [vordgi/nimpl-router#9]
In route / a cookie property was accessed directly with `cookies().get('NEXT_LOCALE')`. `cookies()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
 
 Next 15 will release with async api's for everything, meaning await has to be called when accessing cookies().
 
 Happy to do a PR for this as well

**Comment by vordgi** [comment]
Hello!

Yes, that's an important change, thanks. It would be wonderful if you would create a PR for this.

_If you will decide not to do it - please let me know and I'll add the functionality in the nearest free time_

**Comment by vordgi** [comment]
_Working on this_

**Comment by vordgi** [comment]
- [ ] Update next to v15
- [ ] Support next v15
- [ ] Update example
- [ ] Update docs

**Comment by vordgi** [comment]
Released! v1.0.0 🎉
